### ISSUE TITLE
Merge into github.com/mattes/epeg

### ISSUE THREAD

**Issue by mattes** [koofr/epeg#1]
Hey! I just found your repo and it seems as if you did some tremendous work to epeg. Are you interested in merging back into https://github.com/mattes/epeg?

**Comment by bancek** [comment]
I would be happy to contribute back to original library.

My additions to library were mostly JPEG transformations and error reporting. JPEG transformations are hard to merge back because it requires custom build of libjpeg with `transupp`. Default distrubution of libjpeg does not contain that and it would complicate epeg distribution to different platforms.
